version: '2'
  
services:
  postgresql-test:
    image: 'postgres:13'
    container_name: postgresql-test
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=test
    volumes:
      - ./postgres-data:/var/lib/postgresql-test/data
    restart: unless-stopped
